### ISSUE TITLE
Does not build on Ubuntu 19.04

### ISSUE THREAD

**Issue by bert003** [flathub/com.github.muriloventuroso.easyssh#4]
> [4/27] Compiling Vala source ../src/Ap... ../src/Widgets/BookmarksPopover.vala.
> FAILED: com.github.muriloventuroso.easyssh@exe/src/Application.c com.github.muriloventuroso.easyssh@exe/src/Host.c com.github.muriloventuroso.easyssh@exe/src/Account.c com.github.muriloventuroso.easyssh@exe/src/Bookmark.c com.github.muriloventuroso.easyssh@exe/src/MainWindow.c com.github.muriloventuroso.easyssh@exe/src/Services/Settings.c com.github.muriloventuroso.easyssh@exe/src/Views/SourceListView.c com.github.muriloventuroso.easyssh@exe/src/Widgets/TerminalBox.c com.github.muriloventuroso.easyssh@exe/src/Widgets/Welcome.c com.github.muriloventuroso.easyssh@exe/src/Widgets/WelcomeAccounts.c com.github.muriloventuroso.easyssh@exe/src/Widgets/HeaderBar.c com.github.muriloventuroso.easyssh@exe/src/Widgets/ConnectionEditor.c com.github.muriloventuroso.easyssh@exe/src/Widgets/AccountEditor.c com.github.muriloventuroso.easyssh@exe/src/Widgets/Connection.c com.github.muriloventuroso.easyssh@exe/src/Widgets/ErrorRevealer.c com.github.muriloventuroso.easyssh@exe/src/Widgets/Preferences.c com.github.muriloventuroso.easyssh@exe/src/Widgets/TerminalWidget.c com.github.muriloventuroso.easyssh@exe/src/Widgets/SearchToolbar.c com.github.muriloventuroso.easyssh@exe/src/Widgets/BookmarksPopover.c 
> valac -C --debug --debug --define UBUNTU_BIONIC_PATCHED_VTE --define=UNITY_SUPPORT=1 --define WITH_GPG --pkg unity --pkg gee-0.8 --pkg vte-2.91 --pkg json-glib-1.0 --pkg granite --pkg gtk+-3.0 --pkg glib-2.0 --pkg gee-0.8 --color=always --directory com.github.muriloventuroso.easyssh@exe --basedir ../ --gresources=../data/com.github.muriloventuroso.easyssh.gresource.xml ../src/Application.vala ../src/Host.vala ../src/Account.vala ../src/Bookmark.vala ../src/MainWindow.vala ../src/Services/Settings.vala ../src/Views/SourceListView.vala ../src/Widgets/TerminalBox.vala ../src/Widgets/Welcome.vala ../src/Widgets/WelcomeAccounts.vala ../src/Widgets/HeaderBar.vala ../src/Widgets/ConnectionEditor.vala ../src/Widgets/AccountEditor.vala ../src/Widgets/Connection.vala ../src/Widgets/ErrorRevealer.vala ../src/Widgets/Preferences.vala ../src/Widgets/TerminalWidget.vala ../src/Widgets/SearchToolbar.vala ../src/Widgets/BookmarksPopover.vala
> ../src/Services/Settings.vala:52.17-52.37: warning: unhandled error `GLib.Error'
>                 file.make_directory();
>                 ^^^^^^^^^^^^^^^^^^^^^
> ../src/Widgets/TerminalWidget.vala:120.21-120.30: warning: Gtk.Menu.popup has been deprecated since 3.22
> ../src/Widgets/TerminalWidget.vala:172.13-172.27: warning: Vte.Terminal.spawn_sync has been deprecated since 0.48
> ../src/Widgets/TerminalWidget.vala:172.13-173.101: warning: unhandled error `GLib.Error'
> ../src/Widgets/TerminalWidget.vala:201.33-201.35: error: Argument 1: Cannot convert from `unowned string' to `unowned char[]?'
>                 this.feed_child(cmd, cmd.length);
>                                 ^^^
> ../src/Widgets/TerminalWidget.vala:201.17-201.48: error: 1 extra arguments for `void Vte.Terminal.feed_child (char[]?)'
>                 this.feed_child(cmd, cmd.length);
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ../src/Widgets/SearchToolbar.vala:97.21-97.42: warning: Vte.Terminal.search_set_gregex has been deprecated since 0.46
> ../src/Widgets/TerminalBox.vala:89.33-89.35: error: Argument 1: Cannot convert from `unowned string' to `unowned char[]?'
>                 term.feed_child(cmd, cmd.length);
>                                 ^^^
> ../src/Widgets/TerminalBox.vala:89.17-89.48: error: 1 extra arguments for `void Vte.Terminal.feed_child (char[]?)'
>                 term.feed_child(cmd, cmd.length);
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ../src/Widgets/TerminalBox.vala:190.33-190.37: error: Argument 1: Cannot convert from `unowned string' to `unowned char[]?'
>                 term.feed_child(n_cmd, cmd.length);
>                                 ^^^^^
> ../src/Widgets/TerminalBox.vala:190.17-190.50: error: 1 extra arguments for `void Vte.Terminal.feed_child (char[]?)'
>                 term.feed_child(n_cmd, cmd.length);
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ../src/Widgets/TerminalBox.vala:181.33-181.35: error: Argument 1: Cannot convert from `unowned string' to `unowned char[]?'
>                 term.feed_child(cmd, cmd.length);
>                                 ^^^
> ../src/Widgets/TerminalBox.vala:181.17-181.48: error: 1 extra arguments for `void Vte.Terminal.feed_child (char[]?)'
>                 term.feed_child(cmd, cmd.length);
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ../src/Views/SourceListView.vala:962.21-962.34: warning: unhandled error `GLib.Error'
>                     file.delete ();
>                     ^^^^^^^^^^^^^^
> ../src/Views/SourceListView.vala:964.49-964.97: warning: unhandled error `GLib.Error'
>                 var dos = new DataOutputStream (file.create (FileCreateFlags.REPLACE_DESTINATION));
>                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ../src/Views/SourceListView.vala:966.17-966.37: warning: unhandled error `GLib.IOError'
>                 dos.put_string (data);
>                 ^^^^^^^^^^^^^^^^^^^^^
> ../src/Views/SourceListView.vala:973.25-973.42: warning: unhandled error `GLib.Error'
>                         file_ssh.delete ();
>                         ^^^^^^^^^^^^^^^^^^
> ../src/Views/SourceListView.vala:975.57-975.109: warning: unhandled error `GLib.Error'
>                     var dos_ssh = new DataOutputStream (file_ssh.create (FileCreateFlags.REPLACE_DESTINATION));
>                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ../src/Views/SourceListView.vala:976.21-976.56: warning: unhandled error `GLib.IOError'
>                     dos_ssh.put_string (data_ssh_config);
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ../src/Views/SourceListView.vala:1015.21-1015.34: warning: unhandled error `GLib.Error'
>                     file.delete ();
>                     ^^^^^^^^^^^^^^
> ../src/Views/SourceListView.vala:1017.49-1017.97: warning: unhandled error `GLib.Error'
>                 var dos = new DataOutputStream (file.create (FileCreateFlags.REPLACE_DESTINATION));
>                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ../src/Views/SourceListView.vala:1019.17-1019.37: warning: unhandled error `GLib.IOError'
>                 dos.put_string (data);
>                 ^^^^^^^^^^^^^^^^^^^^^
> ../src/Views/SourceListView.vala:1056.21-1056.34: warning: unhandled error `GLib.Error'
>                     file.delete ();
>                     ^^^^^^^^^^^^^^
> ../src/Views/SourceListView.vala:1058.49-1058.97: warning: unhandled error `GLib.Error'
>                 var dos = new DataOutputStream (file.create (FileCreateFlags.REPLACE_DESTINATION));
>                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ../src/Views/SourceListView.vala:1060.17-1060.37: warning: unhandled error `GLib.IOError'
>                 dos.put_string (data);
>                 ^^^^^^^^^^^^^^^^^^^^^
> ../src/MainWindow.vala:35.9-35.42: warning: EasySSH.MainWindow.application hides inherited property `Gtk.Window.application'. Use the `new' keyword if hiding was intentional
>         public Gtk.Application application { get; construct; }
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ../src/MainWindow.vala:424.13-424.82: warning: unhandled error `GLib.SpawnError'
>             Process.spawn_command_line_async (default_filemanager + " " + command);
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ../src/MainWindow.vala:237.17-240.41: warning: unhandled error `GLib.SpawnError'
> ../src/MainWindow.vala:247.17-250.41: warning: unhandled error `GLib.SpawnError'
> ../src/MainWindow.vala:135.32-135.46: warning: Gtk.ActionGroup has been deprecated since 3.10
> ../src/MainWindow.vala:150.22-150.34: warning: Gtk.UIManager has been deprecated since 3.10
> Compilation failed: 8 error(s), 23 warning(s)
> [5/27] Generating com.github.muriloven...ktop_data_merge with a custom command.
> ninja: build stopped: subcommand failed.
>

**Comment by bilelmoussaoui** [comment]
Not a Flatpak/Flathub issue. Please report upstream.
